# SITE BASICS
title: "ShopSavvy Sahara"
tagline: "Best Deals & Honest Reviews in South Africa"
description: "Honest shopping deals, product reviews, and trends for gadgets, fashion, beauty, and home in 2025."

lang: en
timezone: Africa/Johannesburg

# URL SETTINGS
url: "https://mkhatshwa027-eng.github.io"
baseurl: "/Shopsavvy-sahara"

# THEME
theme: jekyll-theme-chirpy
theme_mode: auto
img_banner: true

# AUTHOR
social:
  name: "Siyabonga Mkhatshwa"
  email: "mkhatshwa027@gmail.com"
  links:
    - https://github.com/mkhatshwa027-eng
    - https://pin.it/76LvaogSH

avatar: /assets/img/Earbud.jpg

# GOOGLE ANALYTICS
google_analytics: "G-91DJBNFWD"

# SIDEBAR
sidebar:
  enabled: true
  categories: true
  tags: true
  recent_posts: 5

# POSTS
paginate: 10
excerpt_link: "Read More â†’"

# COLLECTIONS
collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/

# SASS
sass:
  style: compressed

# HTML COMPRESSION
compress_html:
  clippings: all
  comments: all
  endings: all
  blanklines: false

# ARCHIVES
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
homepage:
  layout: none
